# Generated by Django 2.2.4 on 2019-09-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, default='picture', null=True, upload_to=None, verbose_name='picture'),
        ),
    ]
