# Generated by Django 2.2.1 on 2019-08-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commanderie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom commanderie')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='numéro commanderie')),
                ('date', models.DateField(verbose_name='date de création')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='couriel')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='districte.Section')),
            ],
            options={
                'verbose_name': 'Commanderie',
                'verbose_name_plural': 'Commanderies',
            },
        ),
        migrations.CreateModel(
            name='Chevalier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=100, verbose_name='nom')),
                ('last_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('type_chevalier', models.CharField(choices=[('CHEVALIER', 'CHEVALIER'), ('DAME OXILLIAIRE', 'DAME OXILLIAIRE'), ('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR')], default=[0], max_length=100, verbose_name='type de chevalier')),
                ('grade_chevalier', models.CharField(choices=[('MAJOR', 'MAJOR'), ('BRIGADIER GENERAL', 'BRIGADIER GENERAL'), ('OFFICIE', 'OFFICIE')], default=[0], max_length=100, verbose_name='type de grade')),
                ('date', models.DateField(verbose_name="date d'initiation")),
                ('telephone', models.CharField(max_length=11, verbose_name='telephone')),
                ('adresse', models.CharField(max_length=100, verbose_name='adresse')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('commanderie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commanderie', to='commanderie.Commanderie')),
            ],
            options={
                'verbose_name': 'Chevalier',
                'verbose_name_plural': 'Chevaliers',
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(blank=True, max_length=100, null=True, verbose_name='président')),
                ('vice_president', models.CharField(blank=True, max_length=100, null=True, verbose_name='vice président')),
                ('secrtaire', models.CharField(blank=True, max_length=100, null=True, verbose_name='secretaire')),
                ('vice_secretaire', models.CharField(blank=True, max_length=100, null=True, verbose_name='vice secretaire')),
                ('tresorier', models.CharField(blank=True, max_length=100, null=True, verbose_name='tresorier')),
                ('vice_tresorier', models.CharField(blank=True, max_length=100, null=True, verbose_name='vice tresorier')),
                ('date', models.DateField(verbose_name="date d'installation")),
                ('commanderie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commanderie.Commanderie', verbose_name='commanderie')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaus',
            },
        ),
    ]
