# Generated by Django 2.2.4 on 2019-09-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanderie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'Bureau', 'verbose_name_plural': 'Bureaux'},
        ),
    ]
