# Generated by Django 2.2.2 on 2019-09-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanderie', '0002_auto_20190909_2132'),
        ('commanderie', '0002_auto_20190907_1740'),
    ]

    operations = [
    ]
