# Generated by Django 2.2.1 on 2019-08-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom districte')),
                ('date', models.DateField(verbose_name='date de création')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='couriel')),
            ],
            options={
                'verbose_name': 'Districte',
                'verbose_name_plural': 'Districtes',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom section')),
                ('date', models.DateField(verbose_name='date de création')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='couriel')),
                ('districtes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districte.Districte', verbose_name='districte')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
